blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileAllowed


class BlogPostForm(FlaskForm):
    # no empty titles or text possible
    # we'll grab the date automatically from the Model later
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    category = SelectField('Category', choices=[('politics', 'politics'),('lifestyle','lifestyle'), ('business', 'business'),('sports','sports'), ('story time', 'story time'), ('education', 'education'), ('nostalgia', 'nostalgia'), ('health', 'health')], validators=[DataRequired()])
    blog_image = FileField('Cover Photo', validators=[FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('BlogPost')

blog_posts/views.py
from flask import render_template,url_for,flash, redirect,request,Blueprint
from flask_login import current_user,login_required
from puppycompanyblog import db
from puppycompanyblog.models import BlogPost
from puppycompanyblog.blog_posts.forms import BlogPostForm
from puppycompanyblog.blog_posts.blogimagehandler import add_blog_pic, create_thumbnail

blog_posts = Blueprint('blog_posts',__name__)

@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():

        if form.blog_image.data:

            pic = add_blog_pic(form.blog_image.data)
            pic_thumbnail = create_thumbnail(form.blog_image.data)
            BlogPost.blog_image = pic

            blog_post = BlogPost(title=form.title.data,
                                 text=form.text.data,
                                 category = form.category.data,
                                 user_id=current_user.id,
                                 blog_image=pic,
                                 blog_thumbnail = pic_thumbnail
                                 )
        else:
            blog_post = BlogPost(title=form.title.data,
                                 text=form.text.data,
                                 category = form.category.data,
                                 user_id=current_user.id,
                                  blog_image='c1.jpg',
                                  blog_thumbnail = 'stories1.jpg'
                                 )

        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created")
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)


# int: makes sure that the blog_post_id gets passed as in integer
# instead of a string so we can look it up later.
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    # grab the requested blog post by id number or return 404
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=8)
    latest_posts =BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=4)
    top_posts =BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=4)


    return render_template('readblog.html',title=blog_post.title,
                            date=blog_post.date,post=blog_post, blog_posts=blog_posts, latest_posts=latest_posts, top_posts=top_posts
    )

@blog_posts.route('/<int:blog_post_id>/update', methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        # Forbidden, No Access
        abort(403)

    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))
    # Pass back the old blog post information so they can start again with
    # the old text and title.
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text
    return render_template('create_post.html', title='Update',
                           form=form)


@blog_posts.route("/<int:blog_post_id>/delete", methods=['POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    flash('Post has been deleted')
    return redirect(url_for('core.index'))

core/views.py
from flask import render_template,request,Blueprint
from puppycompanyblog.models import BlogPost

core = Blueprint('core',__name__)

@core.route('/')
def index():
    '''
    This is the home page view. Notice how it uses pagination to show a limited
    number of posts by limiting its query size and then calling paginate.
    '''
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=8)
    latest_posts =BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=4)
    top_posts =BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=4)
    return render_template('index.html',blog_posts=blog_posts, latest_posts=latest_posts, top_posts=top_posts)


@core.route('/info')
def info():
    '''
    Example view of any other "core" page. Such as a info page, about page,
    contact page. Any page that doesn't really sync with one of the models.
    '''
    return render_template('info.html')

@core.route('/politics')
def politics():

    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.filter_by(category='politics').order_by(BlogPost.date.desc()).paginate(page=page, per_page=8)
    latest_posts =BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=4)
    top_posts =BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=4)
    return render_template('politics.html',blog_posts=blog_posts, latest_posts=latest_posts, top_posts=top_posts)

@core.route('/lifestyle')
def lifestyle():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.filter_by(category='lifestyle').order_by(BlogPost.date.desc()).paginate(page=page, per_page=8)
    latest_posts =BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=4)
    top_posts =BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=4)
    return render_template('lifestyle.html',blog_posts=blog_posts, latest_posts=latest_posts, top_posts=top_posts)

@core.route('/business')
def business():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.filter_by(category = 'business').order_by(BlogPost.date.desc()).paginate(page=page, per_page=8)
    latest_posts =BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=4)
    top_posts =BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=4)
    return render_template('business.html',blog_posts=blog_posts, latest_posts=latest_posts, top_posts=top_posts)

@core.route('/sports')
def sports():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.filter_by(category = 'sports').order_by(BlogPost.date.desc()).paginate(page=page, per_page=8)
    latest_posts =BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=4)
    top_posts =BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=4)
    return render_template('sports.html',blog_posts=blog_posts, latest_posts=latest_posts, top_posts=top_posts)

templates/account.html
{% extends "baseadmin.html" %}
{% block content %}
<section class="main-body section-gap"

<div class="jumbotron">
  <div align='center'>
    <h1 >Welcome to the page for {{current_user.username}}</h1>
    <img align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
    <p>{{ current_user.email }}</p>
  </div>
</div>
<div class="container">
  <form  method="POST" action = "" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.username.label(class="form-group") }}
      {{form.username(class='form-control')  }}
    </div
    <div class="form-group">
      {{ form.email.label(class="form-group") }}
      {{form.email(class='form-control')  }}
    </div>
    <div class="form-group">
      {{ form.picture.label(class="form-group") }}
      {{ form.picture(class="form-control-file") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>

</div>

</section>

{% include "footer.html"%}
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>The Daily Scroll</title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,800" rel="stylesheet">
		<link rel="stylesheet" href="../../../static/css/vendor.css">
		<link rel="stylesheet" href="../../../static/css/style-6.css" id="template-skin">
		<link rel="shortcut icon" href="../../static/images/brandedtext.ico" type="image/x-icon">

		<link rel="stylesheet" href="static/css/linearicons.css">
		<link rel="stylesheet" href="static/css/font-awesome.min.css">
		<link rel="stylesheet" href="static/css/bootstrap.css">
		<link rel="stylesheet" href="static/css/magnific-popup.css">
		<link rel="stylesheet" href="static/css/nice-select.css">
		<link rel="stylesheet" href="static/css/animate.min.css">
		<link rel="stylesheet" href="static/css/owl.carousel.css">
		<link rel="stylesheet" href="static/css/main.css">


	</head>
	<body>

		{% with messages = get_flashed_messages(with_categories=true) %}
		  {% if messages %}
		    <div class="alert alert-dismissible fade show" role="alert">
		    {% for category, message in messages %}
		      <div class="{{category}}"> {{ message }}</div>
		    {% endfor %}
			</div>
		  {% endif %}
		{% endwith %}






		<!-- Preload start -->
		<div id="loader-wrapper">
		  <div id="loader"></div>
		  <div class="loader-section section-left"></div>
		  <div class="loader-section section-right"></div>
		</div><!-- Preload end -->
		<!-- To the top start -->
		<div id="to-the-top" class="to-the-top"><a href="#"><i class="fa fa-long-arrow-up"></i></a></div><!-- To the top end -->
		<!-- Mobile menu start -->
		<aside id="offcanvas-menu" data-pushbar-id="left" class="pushbar from_left">
		  <h4 class="title"><span>Site Menu</span><span data-pushbar-close> </span></h4>
		</aside><!-- Mobile menu end -->
		<div id="page" class="page">
		  <div id="content-wrapper" class="content-wrapper">
		    <div class="content-wrapper-inner">
		      <!-- Header start -->
		      <header class="site-header site-header-1">

		        <!-- Top bar start
		        <div class="top-bar">
		          <div class="container">
		            <div class="row">
		              <div class="col-lg-12 top-bar-content">
		                <ul>
		                  <li><a href="#">our team</a></li>
		                  <li><a href="#">Order Now</a></li>
		                  <li><a href="#">newsroom</a></li>
		                  <li><a href="#">careers</a></li>
		                  <li><a href="#">contact us</a></li>
		                </ul>
		                <div class="lang-and-social-buttons">
		                  <ul>
		                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
		                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
		                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
		                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
		                    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
		                  </ul>
		                </div>
		              </div>
		            </div>
		          </div>
		        </div> Top bar end -->

							<!-- Menu bar start -->
							<div id="sticked-bar" class="menu-bar">
								<div class="container">
									<div class="row">
										<div class="col-lg-12 menu-bar-content">
											<!-- Memu start --><button data-pushbar-target="left" class="hidden-lg"><i class="fa fa-bars"></i></button>
											<nav id="site-menu" class="site-menu hidden-sm hidden-xs hidden-md">
												<ul>
													<li class="nav-item">
														<a class="nav-link" href="{{ url_for('core.index') }}">The Daily Scroll</a>
													</li>
													<li class="nav-item">
														<a class="nav-link" href="{{ url_for('core.index') }}">Home</a>
													</li>
													<li class="nav-item">
														<a class="nav-link" href="{{ url_for('core.politics') }}">Politics</a>
													</li>

													<li class="nav-item">
														<a class="nav-link" href="{{ url_for('core.lifestyle') }}">Lifestyle</a>
													</li>
													<li class="nav-item">
														<a class="nav-link" href="{{ url_for('core.business') }}">Business</a>
													</li>
													<li class="nav-item">
														<a class="nav-link" href="{{ url_for('core.sports') }}">Sports</a>
													</li>
													<!--{% if current_user.is_authenticated %}
														<li><a href="{url_for('users.clientarea',client_id=current_user.id)}}">client</a></li>
													{% else %}
														<li><a href="{url_for('users.login')}}">client</a></li>
													{% endif %}

													<li><a href="http://blog.brandedtext.com">blog</a></li>



													{% if current_user.is_authenticated%}
														<li><a href="{url_for('users.logout')}}">Logout</a></li>
													{% else %}
														<li><a href="{url_for('users.login')}}">Login</a>
														<ul>
															<li><a href="{url_for('users.sign')}}">Signup</a></li>
														</ul>
														</li>
													{% endif %}

												</ul> -->
											</nav><!-- Memu end -->
											<!-- Search start -->
											<!--<form class="search-form"><input type="search" placeholder="Search here..."><button type="submit"><span class="wicon-iconmonstr-search-thin"></span></button></form><!-- Search end -->
										</div>
									</div>
								</div>
							</div><!-- Menu bar end -->

						</header><!-- Header end -->

					<!-- Latest blog posts start -->

						{% block content %}

						{% endblock %}





		<!-- bootstrap scripts-->

		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

		<script src="../static/js/vendor.js"></script>
		<script src="../static/js/framework.js"></script>
		<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpVQEdCmd9aY_-N6920-wilfScyBwS-Lw&amp;callback=initMap"></script>
		<script src="../static/js/template.js"></script>


		<script src="static/js/vendor/jquery-2.2.4.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
		 crossorigin="anonymous"></script>
		<script src="static/js/vendor/bootstrap.min.js"></script>
		<script type="static/text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
		<script src="static/js/easing.min.js"></script>
		<script src="static/js/hoverIntent.js"></script>
		<script src="static/js/superfish.min.js"></script>
		<script src="static/js/jquery.ajaxchimp.min.js"></script>
		<script src="static/js/jquery.magnific-popup.min.js"></script>
		<script src="static/js/owl.carousel.min.js"></script>
		<script src="static/js/jquery.tabs.min.js"></script>
		<script src="static/js/jquery.nice-select.min.js"></script>
		<script src="static/js/waypoints.min.js"></script>
		<script src="static/js/mail-script.js"></script>
		<script src="static/js/main.js"></script>



	</body>
</html>

templates/create_post.html
{% extends "base.html" %}
{% block content %}
<section class="main-body section-gap">
<div class="container">
  <form class="form-group" method="POST" action="" enctype="multipart/form-data">
     {{ form.hidden_tag() }}

     <div class="form-group">
     {{ form.title.label(class="form-control-label") }}
     {{ form.title(class="form-control form-control-lg ") }}
     </div>
     <div class="form-group">
     {{ form.text.label(class="form-control-label") }}
     {{ form.text(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
     {{ form.category.label(class="form-control-label") }}
     {{ form.category(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
     {{ form.blog_image.label(class="form-control-label") }}
     {{ form.blog_image(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
         {{ form.submit(class="btn btn-outline-info") }}
     </div>
  </form>

</div>
</section>
{% include "footer.html" %}
{% endblock content %}

templates/entercode.html
{% extends "base.html" %}
{% block content %}
<section class="main-body section-gap">
<div class="jumbotron">

  <h1>You will receive a phone verification code to the number you entered shortly.</h1>
  <p>Enter The Code Below</p>

  <div class="content-section">
    <div class="container">
      <form method="POST">
      <div class="row">

                <div class="col-sm-8">
                  <div class="card">
                    <div class="card-body">
                      {{form.hidden_tag()}}
                      <div class="form-group">
                      {{form.code.label}}
                      {{form.code(class="form-control", id="code", maxlength=6)}}
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-sm-4">
                  <div class="card">
                    <div class="card-body">
                      <div class="form-group">
                      {{form.submit(class="btn btn-primary")}}
                      </div>
                    </div>
                  </div>
                </div>
      </div>
    </div>
  </div>



</div>
</section>

<script type="text/javascript">
// Restricts input for the given textbox to the given inputFilter.
function setInputFilter(textbox, inputFilter) {
  ["input", "keydown", "keyup", "mousedown", "mouseup", "select", "contextmenu", "drop"].forEach(function(event) {
    textbox.addEventListener(event, function() {
      if (inputFilter(this.value)) {
        this.oldValue = this.value;
        this.oldSelectionStart = this.selectionStart;
        this.oldSelectionEnd = this.selectionEnd;
      } else if (this.hasOwnProperty("oldValue")) {
        this.value = this.oldValue;
        this.setSelectionRange(this.oldSelectionStart, this.oldSelectionEnd);
      }
    });
  });
}

//set filter integer only
setInputFilter(document.getElementById("code"), function(value) {
  return /^\d*$/.test(value); });

</script>

{% endblock %}

templates/footer.html
<footer class="site-footer site-footer-1">
<div class="container">
  <div class="row site-footer-content">
    <div class="col-lg-4 col-md-4 site-footer-logo">
        <!-- Logo start --><a href="index.html" title="Walton" class="site-logo">
          <!--<div class="logo-img"><img src="../static/images/logo.png" alt="Walton"></div>-->
          <div class="name-and-tagline">
            <div class="name">Daily Scroll</div>
            <div class="tagline">Avoid Fake News</div>
          </div>
        </a>
      <p>Copyright @ 2019 U.S. <a href="https://dailyscroll.co.ke">DailyScroll</a>, Inc.</p>
    </div>


    <div class="col-md-3 col-md-push-1">
      <div class="widget widget-contacts">
        <h4 class="widget-title">Contact Us</h4>
        <div class="widget-content">
          <!--<p class="title text-heading">BrandedText Inc.</p>
          <p class="address">1064 Maxwell Street<br>Windsor, CT 06095</p>
          <p class="phone">1 (347) 690-1220</p>-->
          <p class="email"><a href="#">newshall@dailyscroll.co.ke</a></p>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-md-push-1">
      <div class="widget widget-follow">
        <h4 class="widget-title">follow us</h4>
        <div class="widget-content">
          <p class="links"><!--<a href="#"><i class="fa fa-facebook"></i></a>--><a href="#"><i class="fa fa-twitter"></i></a><!--<a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-google-plus"></i></a>--></p>
        </div>
      </div>
    </div>
  </div>
</div>
</footer><!-- Footer end -->

templates/index.html
{% extends "base.html" %}
{% block content %}

{% include "topstories.html"%}
{% include "mainbody.html" %}
{% include "footer.html" %}

{% endblock %}

templates/info.html
{% extends "base.html" %}
{% block content %}
<section class="main-body section-gap">
<div class="jumbotron">
  <h1>BrandedText</h1>
  <p>SEO content solution for your business</p>
</div>
</section>
{% endblock %}

templates/login.html
{% extends "baseadmin.html" %}
{% block content %}
<div class="container">
<h4>Kindly login below</h4>
<p>or</p>
<h6><a href="{{url_for('users.login')}}" class="btn btn-primary">Sign Up Here</a></h6>
<form method="POST">
<div class="jumbotron">
	{{form.hidden_tag()}}
	<div class="form-group">
		{{form.email.label}}
		{{form.email(class="form-control")}}
	</div>

	<div class="form-group">
		{{form.password.label}}
		{{form.password(class="form-control")}}
	</div>

	<div class="form-group">{{form.submit(class="btn btn-primary")}}</div>

</div>
</form>
</div>

{% endblock %}

templates/postslider.html
	<!-- Start Post Silder Area -->
	<section class="post-slider-area">
		<div class="container-fluid">
			<div class="row justify-content-center">
				<div class="col-lg-12">
					<div class="owl-carousel active-post-carusel">
						<!-- single carousel item -->
						<div class="single-post-carousel">
							<div class="post-thumb">
								<img class="img-fluid" src="static/img/posts/carousel/post1.jpg" alt="">
							</div>
							<div class="post-details">
								<h2><a href="#">2nd Gen Smoke Alarm get up <br>
										from sleep Daily</a></h2>
								<div class="post-content d-flex justify-content-between">
									<div class="post-meta">
										<div class="thumb"><img src="static/img/author/a1.png" alt=""></div>
										<div class="c-desc">
											<h6>Marvel Maison</h6>
											<p><span class="lnr lnr-calendar-full"></span>13th Oct, 2018</p>
										</div>
									</div>
									<div class="details">
										<p>There is a moment in the life of any aspiring astronomer that it is time to buy that first telescope.
											It’s exciting to think about setting up your own viewing station.</p>
									</div>
								</div>
							</div>
						</div>
						<!-- single carousel item -->
						{% for post in top_posts.items %}
						<div class="single-post-carousel">
							<div class="post-thumb">
								<img class="img-fluid" src="static/img/posts/carousel/post2.jpg" width="640" height="630" alt="">
							</div>
							<div class="post-details">
								<h2><a href="#">{{ post.title[:35] | safe }}</a></h2>
								<div class="post-content d-flex justify-content-between">
									<div class="post-meta">
										<div class="thumb"><img src="{{url_for('static', filename='blog_pics/small/' + post.blog_thumbnail)}}" alt=""></div>
										<div class="c-desc">
											<h6>{{ post.author.username | safe }}</h6>
											<p><span class="lnr lnr-calendar-full"></span>{{ post.date.strftime('%Y-%m-%d') }}</p>
										</div>
									</div>
									<div class="details">
										<p>{{post.text[:200]}} | safe </p>
									</div>
								</div>
							</div>
						</div>
						{% endfor %}
						<!-- single carousel item -->
						<div class="single-post-carousel">
							<div class="post-thumb">
								<img class="img-fluid" src="static/img/posts/carousel/post3.jpg" alt="">
							</div>
							<div class="post-details">
								<h2><a href="#">2nd Gen Smoke Alarm get up <br>
										from sleep Daily</a></h2>
								<div class="post-content d-flex justify-content-between">
									<div class="post-meta">
										<div class="thumb"><img src="static/img/author/a1.png" alt=""></div>
										<div class="c-desc">
											<h6>Marvel Maison</h6>
											<p><span class="lnr lnr-calendar-full"></span>13th Oct, 2018</p>
										</div>
									</div>
									<div class="details">
										<p>There is a moment in the life of any aspiring astronomer that it is time to buy that first telescope.
											It’s exciting to think about setting up your own viewing station.</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Start Post Silder Area -->

templates/signup.html
{% extends "baseadmin.html" %}
{% block content %}

<div class="container">
	<h4>Kindly sign up below</h4>
	<div><p>Already have an account?</p><h6><a href="{{url_for('users.login')}}" class="btn btn-primary">Login Here</a></h6></div>

<form method='POST' onsubmit="return(validate())" name="form">
<div class="jumbotron">
	{{form.hidden_tag()}}

	<div class="form-group">
	{{form.email.label}}
	{{form.email(class="form-control", id="email")}}
	</div>

	<div class="form-group">
	{{form.username.label}}
	{{form.username(class="form-control")}}
	</div>

	<div class="form-group">
	{{form.password.label}}
	{{form.password(class="form-control", id="password")}}
	</div>


	<div class="form-group">
	{{form.pass_confirm.label}}
	{{form.pass_confirm(class="form-control")}}
	</div>

	<div class="form-check"
		<div class="form-check-input">{{form.checkbox}}</div>
		<div class="form-check-label">{{form.checkbox.label}}</div>
      	</div>

	<div class="form-group">
	{{form.submit(class="btn btn-primary")}}
	</div>

</div>
</form>
</div>
<script type = "text/javascript">

      // Form validation code will come here.
      function validate() {


				 var emailID = document.getElementById("email").value;
				 var pass = document.getElementById("password").value;
         atpos = emailID.indexOf("@");
         dotpos = emailID.lastIndexOf(".");

         if( emailID == ""  || atpos < 1 || ( dotpos - atpos < 2 )) {
            alert( "Please enter a valid email address!" );
            document.getElementById("email").focus() ;
            return false;
         }
         if( pass == ""  || pass.length < 8) {
            alert( "Your password must be atleast 8 characters long" );
            document.getElementById("password").focus() ;
            return false;
         }
			 }



</script>
{% endblock %}

templates/sports.html
{% extends "base.html" %}
{% block content %}

{% include "topstories.html"%}

{% include "mainbody.html" %}
{% include "footer.html" %}

{% endblock %}

templates/user_blog_posts.html
{% extends "baseadmin.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1 >Welcome to the page for {{user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
    </div>
  </div>


{% for post in blog_posts.items %}

          <h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
          Written by: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <p class="text-muted">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
          <br>
            <p>{{post.text | safe}}</p>
          <br>

{% endfor %}


</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {# http://flask.pocoo.org/snippets/44/ #}

    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if blog_posts.page == page_num %}
              <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
    {% endfor %}
</nav>
{% endblock content %}